/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import com.sun.istack.internal.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS TP 450 LDV
 */
public class Frame_Pemesanan extends javax.swing.JFrame {

    public Frame_Pemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtHarga = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtKTP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateTanggal = new com.toedter.calendar.JDateChooser();
        cbTempatDuduk = new javax.swing.JComboBox<>();
        txtWaktu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStasiunAwal = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnClear1 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtStasiunTujuan = new javax.swing.JTextField();
        txtJK = new javax.swing.JTextField();
        btnClear2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("David", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pemesanan Tiket Kereta");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(31, 29, 295, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("SMK TELKOM MALANG");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(31, 59, 124, 15);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(754, 134, 0, 0);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 90, 1180, 10);

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtHarga);
        txtHarga.setBounds(180, 450, 200, 30);

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama);
        txtNama.setBounds(180, 130, 200, 30);

        txtKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKTPActionPerformed(evt);
            }
        });
        jPanel1.add(txtKTP);
        txtKTP.setBounds(180, 170, 200, 30);

        jLabel4.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 27, 12);

        jLabel5.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No.KTP");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 180, 50, 12);

        jLabel6.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Stasiun Awal");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 220, 110, 12);

        jLabel7.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stasiun Tujuan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 260, 120, 12);

        jLabel8.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tanggal Keberangkatan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 300, 130, 12);

        jLabel9.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Kereta");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 340, 70, 12);

        jLabel10.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Waktu Keberangkatan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 380, 130, 12);

        jLabel11.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tempat Duduk");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 420, 80, 12);
        jPanel1.add(dateTanggal);
        dateTanggal.setBounds(180, 290, 200, 30);

        cbTempatDuduk.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        cbTempatDuduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5", "Gerbong 6", "Gerbong 7" }));
        jPanel1.add(cbTempatDuduk);
        cbTempatDuduk.setBounds(180, 410, 200, 30);
        jPanel1.add(txtWaktu);
        txtWaktu.setBounds(180, 370, 200, 30);

        jLabel12.setFont(new java.awt.Font("David", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Harga");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(30, 460, 34, 12);
        jPanel1.add(txtStasiunAwal);
        txtStasiunAwal.setBounds(180, 210, 200, 30);

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(400, 130, 80, 30);

        btnRefresh.setText("PRIVIEW");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh);
        btnRefresh.setBounds(800, 130, 80, 30);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "No.KTP", "Stasiun Awal", "Stasiun Akhir", "Tgl Keberangkatan", "Jenis Kereta", "Wkt Keberangkatan", "Tempat Duduk", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 170, 760, 110);

        btnClear1.setText("CLEAR");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear1);
        btnClear1.setBounds(500, 130, 80, 30);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete);
        btnDelete.setBounds(600, 130, 80, 30);
        jPanel1.add(txtStasiunTujuan);
        txtStasiunTujuan.setBounds(180, 250, 200, 30);

        txtJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJKActionPerformed(evt);
            }
        });
        jPanel1.add(txtJK);
        txtJK.setBounds(180, 330, 200, 30);

        btnClear2.setText("PRINT");
        jPanel1.add(btnClear2);
        btnClear2.setBounds(700, 130, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1180, 510);

        setSize(new java.awt.Dimension(1200, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKTPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKTPActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
                            //Tanggal
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); 
        String tanggal = dateFormat.format(dateTanggal.getDate());
                            //Input Data
        if("".equals(txtNama.getText()) || "".equals(txtKTP.getText()) || "".equals(txtStasiunAwal.getText()) || "".equals(txtWaktu.getText()) || tanggal.equals("") || "".equals(txtJK.getText()) || "".equals(txtWaktu.getText()) || "".equals(cbTempatDuduk.getSelectedItem()) || "".equals(txtHarga.getText())){
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO tb_pesan (Nama_Pemesan,No_ID,Stasion_Awal,Stasion_Tujuan,Tanggal_Berangkat,Jenis_Kereta,Waktu_Berangkat,Tempat_Duduk,Harga)"
                    + "VALUES('"+txtNama.getText()+"','"+txtKTP.getText()+"','"+txtStasiunAwal.getText()+"','"+txtStasiunTujuan.getText()+"',"
                    + "'"+tanggal+"','"+txtJK.getText()+"','"+txtWaktu.getText()+"','"+cbTempatDuduk.getSelectedItem()+"','"+txtHarga.getText()+"')";
            int status = koneksiDB.execute(SQL);
            if (status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan!", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJKActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        txtNama.setText("");
        txtKTP.setText("");
        txtStasiunAwal.setText("");
        txtStasiunTujuan.setText("");
        dateTanggal.setDateFormatString("");
        txtJK.setText("");
        txtWaktu.setText("");
        cbTempatDuduk.setToolTipText("");
        txtHarga.setText("");
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int baris =tblData.getSelectedRow();
        if (baris != -1) {
        String No_ID = tblData.getValueAt(baris, 1).toString();
        String SQL = "DELETE FROM tb_pesan WHERE No_ID='"+No_ID+"'";
        int status = koneksiDB.execute(SQL);
            if (status==1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus!", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClear2;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbTempatDuduk;
    private com.toedter.calendar.JDateChooser dateTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJK;
    private javax.swing.JTextField txtKTP;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtStasiunAwal;
    private javax.swing.JTextField txtStasiunTujuan;
    private javax.swing.JTextField txtWaktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Nama_Pemesan,No_ID,Stasion_Awal,Stasion_Tujuan,Tanggal_Berangkat,Jenis_Kereta,Waktu_Berangkat,Tempat_Duduk,Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pesan";
        ResultSet rs = koneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String Nama_Pemesan = rs.getString(1);
                String No_ID = rs.getString(2);
                String Stasion_Awal = rs.getString(3);
                String Stasion_Tujuan = rs.getString(4);
                String Tanggal_Berangkat = rs.getString(5);
                String Jenis_Kereta = rs.getString(6);
                String Waktu_Berangkat = rs.getString(7);
                String Tempat_Duduk = rs.getString(8);
                String Harga = rs.getString(9);
                String data[] = {Nama_Pemesan,No_ID,Stasion_Awal,Stasion_Tujuan,Tanggal_Berangkat,Jenis_Kereta,Waktu_Berangkat,Tempat_Duduk,Harga};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(Frame_Pemesanan.class).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);
        
    }
}
